name: CI pipline
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
